platform :ios, '9.0'

target 'ChargeMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChargeMe

  pod 'lottie-ios'
  pod 'GravitySliderFlowLayout'
  pod 'moa', '~> 10.0'
  pod 'Auk', '~> 9.0'


end
